# Generated by Django 5.2.7 on 2025-10-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='correo',
            new_name='email',
        ),
    ]
